version: '3'
services:
  postgres:
    image: postgres:bullseye
    environment:
      POSTGRES_DB: kt1Database
      POSTGRES_USER: kukakryak
      POSTGRES_PASSWORD: m0stun1qu3p4ssw0rd
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kukakryak@gogole.com
      PGADMIN_DEFAULT_PASSWORD: 4n0th3run1qu3p4ssw0rd
    ports:
      - "80:80"